# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

#BASE_PATH : http://blog.ankanbiswas.in/uno-dbyll
BASE_PATH : http://lihexiang.top

description : 未来不迎，当下不杂，既过不恋
title : Kevin Lee
logo : /assets/images/avatar.jpg
#cover : /assets/images/background-cover.jpg


intensedebate_comments: true

author:
  name: Kevin Lee
  maxim: Stay hungry,Stay foolish
  role: Jekyll Theme
  email: lihexiang2012@163.com
  github: LiHexiang
  twitter: lihexiang
  facebook: lihexiang
  googleplus: +lihexiang
  bio: "Hi, 我是Kevin Lee"
  uno-dbyll: /assets/images/avatar.jpg
